#!/bin/bash

#This is a keapalive script for my OpenVPN clients
#This script will ping the server twice
#If successful, it will print such to syslog
#If it fails, it will restart the interface specified
#as well as the OpenVPN client service
#For this to work properly, the correct interface must be specified
#The OpenVPN client connection must also be set to autoconnect in:
#/etc/default/openvpn
#Use AUTOSTART="all"
#And ensure that the client.ovpn has been renamed client.conf and is
#stored in: /etc/openvpn

#Script to ping server

#Global Variables
now=$(date)
interface=$(/sbin/ip -o -4 route show to default |awk '{print $6}')
serveraddress=10.8.0.1
log=/var/log/syslog
scriptpath=$(pwd)/customRestart.sh

if [ -f /etc/default/openvpn ];
then
	echo "OpenVPN default file exists."
else
	echo '/etc/default/openvpn does not exist.'
	echo 'Do you want to install OpenVPN now? (y/n)'
	read yesno

	if [ $yesno == "y" ];
	then
#		sudo apt-get install openvpn
		echo $yesno "Installing OpenVPN"
	else
		echo "This script requires /etc/default/openvpn to run properly. Exiting"
#		exit
	fi
fi

if [ -f ./customRestart.sh ];
then
	echo 'customRestart.sh already exists in this directory! Exiting'
	exit
fi

echo "Enter primary network interface. Enter for default. (Your default route is using $interface):" 
read interfaceIn

if [ -z "$interfaceIn" ];
then
	echo "Using default."
else
	interface=$interfaceIn
fi

echo "Enter primary VPN Server Address (Default is 10.8.0.1): "
read serveraddressIn

if [ -z "$serveraddressIn" ];
then
	echo "Using default."
else
	serveraddress=$serveraddressIn	
fi

echo "Enter log location (Default is /var/log/syslog): "
read logIn

if [ -z "$logIn" ];
then
	echo "Using default."
else
	log=$logIn	
fi

echo '#!/bin/bash' >> customRestart.sh
echo "#Autogenerated OpenVPN Keepalive cron script\n" >> customRestart.sh
echo 'now=$(date)' >> customRestart.sh

echo "if ping -c 2 $serveraddress &> /dev/null;" >> customRestart.sh
echo 'then' >> customRestart.sh
echo "	echo \"\$now OpenVPN keepalive successful\" >> $log" >> customRestart.sh
echo 'else' >> customRestart.sh
echo "	echo \"\$now OpenVPN keepalive failed\" >> $log" >> customRestart.sh
echo "	echo \"\$now Restarting Networking\" >> $log" >> customRestart.sh
echo "	/sbin/ifdown $interface" >> customRestart.sh
echo "	/sbin/ifup $interface" >> customRestart.sh
echo '	sleep 30' >> customRestart.sh 

echo "	echo \"\$now Restarting OpenVPoopN\" >> $log" >> customRestart.sh
echo "	/etc/init.d/openvpn restart >> $log" >> customRestart.sh
echo 'fi' >> customRestart.sh
 
chmod 700 customRestart.sh

#(crontab -l ; echo "*/$interval * * * * $scriptpath")| crontab -

echo 'Script completed successfully.\nA new script customRestart.sh should now exist in your current directory.\nNOTE: This script cannot be moved or renamed or the cronjob will fail!\n'
